DROP_TABLE_PLAYERS="""
    DROP TABLE IF EXISTS players
"""

DROP_TABLE_TEAMS="""
    DROP TABLE IF EXISTS teams
"""

DROP_TABLE_ITEMS="""
    DROP TABLE IF EXISTS items
"""

DROP_TABLE_TEAMS_ITEMS="""
    DROP TABLE IF EXISTS teams_items
"""

DROP_TABLE_PLAYERS_ITEMS="""
    DROP TABLE IF EXISTS players_items
"""